#!/usr/bin/env bash
set -euo pipefail

IMAGE_TAG="${IMAGE_TAG:-ghcr.io/zeroclaw-labs/zeroclaw:debian}"

ask() { local p="$1" d="$2" a; read -rp "$p [$d]: " a; printf '%s' "${a:-$d}"; }

command -v docker >/dev/null || { echo "ERROR: docker not found"; exit 1; }

echo "===================================================="
echo "  ZeroClaw assistant installer"
echo "===================================================="
echo

NAME="$(ask 'Instance name' 'default')"
INSTANCE="$(printf '%s' "$NAME" | tr '[:upper:]' '[:lower:]' | tr -c 'a-z0-9_-' '-' | sed 's/-\{2,\}/-/g; s/^-//; s/-$//')"
[ -n "$INSTANCE" ] || INSTANCE="default"
TARGET="/opt/zeroclaw/${INSTANCE}"
PROJECT="$INSTANCE"

echo
echo "Expose the gateway on which host interface?"
echo "  1) 127.0.0.1   this VM only (reach it via an SSH tunnel)"
echo "  2) 0.0.0.0     all interfaces / LAN"
case "$(ask 'Choose 1 or 2' '2')" in
  1) BIND_IP="127.0.0.1" ;;
  *) BIND_IP="0.0.0.0" ;;
esac

PORT="$(ask 'Port' '42617')"

case "$(ask 'Include the web dashboard? (y/n)' 'y')" in
  [Yy]*) DASHBOARD=1 ;;
  *)     DASHBOARD=0 ;;
esac

echo
echo "==> Pulling ${IMAGE_TAG} ..."
docker pull -q "$IMAGE_TAG" >/dev/null
IMAGE_REF="$(docker image inspect "$IMAGE_TAG" --format '{{index .RepoDigests 0}}')"
[ -n "$IMAGE_REF" ] || IMAGE_REF="$IMAGE_TAG"
VERSION="$(docker run --rm --entrypoint zeroclaw "$IMAGE_REF" --version 2>/dev/null | grep -oE '[0-9]+\.[0-9]+\.[0-9]+' | head -1)"
echo "==> ZeroClaw v${VERSION:-unknown}"

mkdir -p "$TARGET/data"

WEB_VOLUME=""
WEB_ENV=""
if [ "$DASHBOARD" = "1" ]; then
  [ -n "$VERSION" ] || { echo "ERROR: could not detect version for the dashboard"; exit 1; }
  echo "==> Fetching web dashboard v${VERSION} ..."
  rm -rf "$TARGET/web.new"; mkdir -p "$TARGET/web.new"
  curl -fsSL "https://github.com/zeroclaw-labs/zeroclaw/releases/download/v${VERSION}/zeroclaw-x86_64-unknown-linux-gnu.tar.gz" | tar -xz --strip-components=2 -C "$TARGET/web.new" web/dist
  test -f "$TARGET/web.new/index.html" || { echo "ERROR: dashboard download failed"; exit 1; }
  rm -rf "$TARGET/web"; mv "$TARGET/web.new" "$TARGET/web"
  WEB_VOLUME=$'\n      - ./web:/web:ro'
  WEB_ENV=$'\n      ZEROCLAW_WEB_DIST_DIR: "/web"'
fi

echo "==> Writing ${TARGET}/docker-compose.yml ..."
cat > "$TARGET/docker-compose.yml" <<YAML
name: ${PROJECT}
services:
  zeroclaw:
    image: ${IMAGE_REF}
    restart: unless-stopped
    ports:
      - "${BIND_IP}:${PORT}:42617"
    volumes:
      - ./data:/zeroclaw-data${WEB_VOLUME}
    environment:
      ZEROCLAW_GATEWAY_HOST: "0.0.0.0"
      ZEROCLAW_ALLOW_PUBLIC_BIND: "1"${WEB_ENV}
    depends_on:
      data-init:
        condition: service_completed_successfully
  data-init:
    image: busybox
    restart: "no"
    volumes:
      - ./data:/zeroclaw-data
    command: ["chmod", "777", "/zeroclaw-data"]
YAML

echo "==> Writing ${TARGET}/manage.sh ..."
cat > "$TARGET/manage.sh" <<MANAGE_HEAD
#!/usr/bin/env bash
set -euo pipefail
INSTANCE="${INSTANCE}"
IMAGE_TAG="${IMAGE_TAG}"
PORT="${PORT}"
DASHBOARD="${DASHBOARD}"
MANAGE_HEAD
cat >> "$TARGET/manage.sh" <<'MANAGE_BODY'

# ---------------------------------------------------------------------------
# Per-instance management helper (generated by zeroclaw-create.sh).
# Run as root from anywhere; it always operates on its own directory.
#   sudo ./manage.sh {start|stop|restart|backup|update|logs|onboard|health}
# ---------------------------------------------------------------------------

DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$DIR"

dc() { docker compose "$@"; }

cmd_start() {
  echo "==> Starting ${INSTANCE} ..."
  dc up -d
}

cmd_stop() {
  echo "==> Stopping ${INSTANCE} ..."
  dc stop
}

cmd_restart() {
  echo "==> Restarting ${INSTANCE} ..."
  dc restart
}

# Snapshot the data dir (config.toml, secrets.key, *.db memory, receipts/).
# The regenerable workspace/cache is excluded; backups/ is a sibling of data/
# so the archive never recurses into itself.
cmd_backup() {
  mkdir -p "$DIR/backups"
  local ts archive
  ts="$(date +%F-%H%M%S)"
  archive="$DIR/backups/zeroclaw-${INSTANCE}-${ts}.tar.gz"
  echo "==> Backing up data/ (excluding workspace/cache) ..."
  tar czf "$archive" -C "$DIR" --exclude='data/workspace/cache' data
  echo "==> Backup written: ${archive}"
}

# stop -> backup (cold, consistent) -> pull latest stable image ->
# re-pin its digest -> refresh the version-matched dashboard -> start -> health.
cmd_update() {
  echo "==> Updating ${INSTANCE} ..."
  cmd_stop
  cmd_backup
  echo "==> Pulling ${IMAGE_TAG} ..."
  docker pull -q "$IMAGE_TAG" >/dev/null
  local new_ref version
  new_ref="$(docker image inspect "$IMAGE_TAG" --format '{{index .RepoDigests 0}}')"
  [ -n "$new_ref" ] || new_ref="$IMAGE_TAG"
  version="$(docker run --rm --entrypoint zeroclaw "$new_ref" --version 2>/dev/null | grep -oE '[0-9]+\.[0-9]+\.[0-9]+' | head -1 || true)"
  echo "==> ZeroClaw v${version:-unknown}"
  # Re-pin only the zeroclaw image line; the busybox data-init line is left alone.
  sed -i "s|image: ghcr.io/zeroclaw.*|image: ${new_ref}|" "$DIR/docker-compose.yml"
  # Refresh the dashboard, but never let a transient fetch failure leave the
  # service stopped: stage into web.new, swap only on success, otherwise keep
  # the existing dashboard and carry on to start (new binary, old dashboard).
  if [ "$DASHBOARD" = "1" ]; then
    if [ -z "$version" ]; then
      echo "WARNING: could not detect version; keeping the existing dashboard. Re-run 'update' to retry."
    else
      echo "==> Refreshing web dashboard v${version} ..."
      rm -rf "$DIR/web.new"; mkdir -p "$DIR/web.new"
      if curl -fsSL "https://github.com/zeroclaw-labs/zeroclaw/releases/download/v${version}/zeroclaw-x86_64-unknown-linux-gnu.tar.gz" | tar -xz --strip-components=2 -C "$DIR/web.new" web/dist && test -f "$DIR/web.new/index.html"; then
        rm -rf "$DIR/web"; mv "$DIR/web.new" "$DIR/web"
      else
        echo "WARNING: dashboard refresh failed; keeping the existing dashboard. Re-run 'update' to retry."
        rm -rf "$DIR/web.new"
      fi
    fi
  fi
  cmd_start
  cmd_health
}

# Non-fatal: show container state, then probe the gateway until it warms up.
# A path/version mismatch must not make a clean update look failed.
cmd_health() {
  echo "==> Service status:"
  dc ps
  echo "==> Probing http://127.0.0.1:${PORT}/health ..."
  local i code=""
  for i in 1 2 3 4 5 6 7 8 9 10; do
    code="$(curl -s -o /dev/null -w '%{http_code}' "http://127.0.0.1:${PORT}/health" 2>/dev/null || true)"
    [ "$code" = "200" ] && { echo "==> /health -> 200 OK"; return 0; }
    sleep 2
  done
  echo "==> /health did not return 200 (last: ${code:-no response}); the gateway may still be warming up."
  echo "    Re-check the /health/* endpoints with: curl -i http://127.0.0.1:${PORT}/health"
}

cmd_logs()    { dc logs -f; }
cmd_onboard() { dc exec zeroclaw zeroclaw onboard; }

usage() {
  echo "Usage: sudo ./manage.sh {start|stop|restart|backup|update|logs|onboard|health}"
  echo
  echo "  start     bring the instance up         (docker compose up -d)"
  echo "  stop      halt the instance             (docker compose stop)"
  echo "  restart   restart the container"
  echo "  backup    snapshot data/ -> backups/    (excludes workspace/cache)"
  echo "  update    stop -> backup -> pull latest image + dashboard -> start -> health"
  echo "  logs      follow logs                   (pairing code shown on boot)"
  echo "  onboard   re-run console onboarding"
  echo "  health    show status + probe /health"
}

case "${1:-}" in
  start)   cmd_start ;;
  stop)    cmd_stop ;;
  restart) cmd_restart ;;
  backup)  cmd_backup ;;
  update)  cmd_update ;;
  logs)    cmd_logs ;;
  onboard) cmd_onboard ;;
  health)  cmd_health ;;
  *)       usage; exit 1 ;;
esac
MANAGE_BODY
chmod +x "$TARGET/manage.sh"

echo "==> Starting ${PROJECT} ..."
( cd "$TARGET" && docker compose up -d )

if [ -t 0 ] && [ -t 1 ]; then
  echo
  echo "==> Onboarding ${PROJECT} ..."
  ( cd "$TARGET" && docker compose exec zeroclaw zeroclaw onboard ) || true
  ( cd "$TARGET" && docker compose restart zeroclaw >/dev/null 2>&1 ) || true
else
  echo "==> No TTY; run onboarding later with:"
  echo "    cd ${TARGET} && docker compose exec zeroclaw zeroclaw onboard"
fi

sleep 3
CODE="$( ( cd "$TARGET" && docker compose logs --no-color 2>&1 ) | grep -oE 'X-Pairing-Code: [0-9]+' | tail -1 || true)"
IP="$(hostname -I 2>/dev/null | awk '{print $1}')"
echo "===================================================="
echo "  Instance:       ${INSTANCE}  (${TARGET})"
if [ "$BIND_IP" = "127.0.0.1" ]; then
  echo "  URL (VM-local): http://127.0.0.1:${PORT}/"
  echo "  Tunnel:         ssh -L ${PORT}:127.0.0.1:${PORT} <user>@${IP:-<vm-ip>}"
else
  echo "  URL:            http://${IP:-<vm-ip>}:${PORT}/"
fi
echo "  Manage:         cd ${TARGET} && ./manage.sh {start|stop|backup|update}"
[ -n "$CODE" ] && echo "  ${CODE}"
echo "===================================================="
